# Generated by Django 5.0.6 on 2024-06-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='city',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='description',
        ),
        migrations.AddField(
            model_name='landmark',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='countries.country'),
            preserve_default=False,
        ),
    ]
