# Generated by Django 5.0.6 on 2024-06-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_alter_city_country_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='country_flags/'),
        ),
    ]
