# Generated by Django 5.0.6 on 2024-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.AddField(
            model_name='landmark',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
