# Generated by Django 5.0.6 on 2024-06-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='country',
        ),
        migrations.AddField(
            model_name='landmark',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='countries.city'),
            preserve_default=False,
        ),
    ]
