# Generated by Django 5.0.6 on 2024-06-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_remove_landmark_country_landmark_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.city'),
        ),
    ]
