# Generated by Django 5.0.6 on 2024-06-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0009_alter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='countries.city'),
        ),
    ]
